# Generated by Django 4.2.6 on 2023-10-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0003_alter_price_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="source",
            field=models.CharField(
                choices=[("FORM", "Form"), ("API", "API")], default="FORM", verbose_name="Currency"
            ),
        ),
    ]
