# Generated by Django 4.2.6 on 2023-10-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_price_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="product_in_off",
            field=models.BooleanField(blank=True, null=True, verbose_name="Product in OFF?"),
        ),
        migrations.AddField(
            model_name="price",
            name="product_off_name",
            field=models.CharField(blank=True, null=True, verbose_name="Product name (OFF)"),
        ),
        migrations.AddField(
            model_name="price",
            name="product_off_db",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OFF", "OpenFoodFacts"),
                    ("OPF", "OpenProductFacts"),
                    ("OPFF", "OpenPetFoodFacts"),
                    ("OBF", "OpenBeautyFacts"),
                ],
                null=True,
                verbose_name="Product OFF DB",
            ),
        ),
    ]
