# Generated by Django 4.2.6 on 2023-10-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0004_price_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="source",
            field=models.CharField(choices=[("FORM", "Form"), ("API", "API")], default="FORM", verbose_name="Source"),
        ),
    ]
