# Generated by Django 4.2.6 on 2023-11-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0006_price_product_off_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="location_osm_lat",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=11, null=True, verbose_name="Location latitude (OSM)"
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="location_osm_lon",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=11, null=True, verbose_name="Location longitude (OSM)"
            ),
        ),
        migrations.AddField(
            model_name="price",
            name="location_osm_type",
            field=models.CharField(
                blank=True,
                choices=[("NODE", "Node"), ("WAY", "Way"), ("RELATION", "Relation")],
                null=True,
                verbose_name="Location type (OSM)",
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="location_name",
            field=models.CharField(blank=True, null=True, verbose_name="Location name (OSM)"),
        ),
        migrations.AlterField(
            model_name="price",
            name="location_osm_id",
            field=models.PositiveBigIntegerField(verbose_name="Location ID (OSM)"),
        ),
    ]
