# Generated by Django 4.2.6 on 2023-11-01 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0007_price_location_osm_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="price",
            old_name="location_name",
            new_name="location_osm_name",
        ),
    ]
