# Generated by Django 4.2.6 on 2023-11-02 11:04

from django.db import migrations


def link_product_code(apps, schema_editor):
    Price = apps.get_model("prices", "Price")
    Product = apps.get_model("products", "Product")
    for p in Price.objects.all():
        if p.product_code is not None:
            product, created = Product.objects.get_or_create(
                code=p.product_code,
                defaults={
                    "in_off": p.product_in_off,
                    "off_db": p.product_off_db,
                    "off_name": p.product_off_name,
                    "off_image_url": p.product_off_image_url,
                },
            )
            p.product_code_link = product
            p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0009_price_product_code_link"),
    ]

    operations = [
        migrations.RunPython(link_product_code),
    ]
