# Generated by Django 4.2.6 on 2023-11-02 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("prices", "0011_price_product_cleanup_and_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="locations.location",
                verbose_name="Location (OSM)",
            ),
        ),
    ]
