# Generated by Django 4.2.6 on 2023-11-02 12:55

from django.db import migrations


def link_location(apps, schema_editor):
    Price = apps.get_model("prices", "Price")
    Location = apps.get_model("locations", "Location")
    for p in Price.objects.all():
        if p.location_osm_id is not None and p.location_osm_type is not None:
            location, created = Location.objects.get_or_create(
                osm_id=p.location_osm_id,
                osm_type=p.location_osm_type,
                defaults={
                    "osm_display_name": p.location_osm_name,
                    "osm_lat": p.location_osm_lat,
                    "osm_lon": p.location_osm_lon,
                },
            )
            p.location = location
            p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0012_price_location"),
    ]

    operations = [
        migrations.RunPython(link_location),
    ]
